services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    univ_lorraine_symfony_cas.authentication_controller:
        class: UnivLorraine\Bundle\SymfonyCasBundle\Controller\AuthenticationController
        public: true
        calls:
            - setContainer: ['@service_container']
        tags:
            - container.service_subscriber

    univ_lorraine_symfony_cas.authentication_service:
        class: UnivLorraine\Bundle\SymfonyCasBundle\Services\CasAuthenticationService
        public: false
        arguments:
            $config: null  # ou la valeur appropri√©e
            $env: '%kernel.environment%'

    UnivLorraine\Bundle\SymfonyCasBundle\Services\CasAuthenticationService: '@univ_lorraine_symfony_cas.authentication_service'
